FROM node:20-alpine

RUN mkdir -p /app
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# COPY PACKAGE DEPENDENCIES
COPY package.json ./

RUN yarn install

COPY . .

CMD yarn serve